controllers/AdminController.php
<?php

namespace app\controllers;


use app\models\Sections;
use app\models\Settings;
use Yii;
use yii\web\NotFoundHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\Json;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use app\models\User;
use app\components\Helper;
use yii\web\Response;


class AdminController extends AppController
{

    public $layout = 'admin';


    /**
     * @param $action
     * @return bool
     * @throws \yii\base\ExitException
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        /* @var $user \app\models\User */
        if (Yii::$app->user->isGuest && $action->id!='login'){
            Yii::$app->response->redirect(Url::to(['admin/login']), 301);
            Yii::$app->end();
        }

        return parent::beforeAction($action);
    }


    /**
     * @return array
     * Запрещаем всем на админам да и вообще пбесправным пользователям заходить
     * сюда. Только POST
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => \yii\filters\VerbFilter::className(),
                'actions' => [
                    'delete-file' => ['POST'],
                ],
            ],
        ];

    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['admin/index']);
        }

        $user = new User(['scenario' => User::SCENARIO_LOGIN]);
        if ($user->load(Yii::$app->request->post()) && $user->validate()){

            $duration = $user->rememberMe ? 0 : 3600 * 24 * 60;

            $checkUser = User::find()
                ->where(['email'=>$user->email])
                ->one();
            if ($checkUser!==null && Yii::$app->security->validatePassword($user->password, $checkUser->password_hash)) {
                /** @var $checkUser \yii\web\IdentityInterface */
                if (Yii::$app->user->login($checkUser, $duration)) {
                    return $this->redirect(['admin/index']);
                }
            }


        }

        return  $this->render('login', [
            'model' => $user,
        ]);

    }

    /**
     *
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionSettings()
    {
        $model = Settings::getModel();

        $this->view->params['breadcrumbs']=['label'=>'Общие настройки'];

        if ($model->load(Yii::$app->request->post())  && $model->save()) {
           return $this->redirect(Url::current());
        }

        return $this->render('settings', [
            'model' => $model,
        ]);
    }

    /**
     * @param $section_id
     * @throws NotFoundHttpException
     */
    public function actionSections($section_id)
    {
        if (!in_array($section_id,[1,2,3,4]))
            return $this->notFound();

        $model = Sections::getModel($section_id);

        $this->view->params['breadcrumbs']=[
            ['label'=>'Секция №'.$section_id]
        ];


        $view = 'section'.$section_id;

        if ($model->load(Yii::$app->request->post())  && $model->validate())
        {
            $model->save(false);
            Yii::$app->session->setFlash('info','Данные сохранены');
            return $this->redirect(['admin/sections','section_id'=>$section_id]);
        }

        return $this->render($view,compact('model'));
    }

    /**
     * @param $section_id
     * @param $field_id
     */
    public function actionDeleteFile($section_id,$field_id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = Sections::getModel($section_id);
        if (!$model)
            return ['status'=>'error'];
        $field = 'image'.$field_id.'_src';

        try
        {
            unlink(Yii::getAlias('@images/'.$model->{$field}));

        }
        catch (\Exception $e )
        {

        }

        $model->updateAttributes([$field=>'']);
        return ['status'=>'OK'];

    }



}

views/admin/error.php
<?php
/**
 * Created by PhpStorm.
 * User: pomazkinis
 * Date: 19.08.2019
 * Time: 13:03
 */
?>

views/admin/index.php
<?php
/**
 * Created by PhpStorm.
 * User: pomazkinis
 * Date: 19.08.2019
 * Time: 15:22
 */

use yii\helpers\Url;
use yii\helpers\Html;
?>
<div class="container">
    <?=Html::tag('h1','Админка');?>

    <div class="col-md-4 col-xs-12">
        <?=Html::tag('h2','Общее')?>
        <?=Html::a('Настройки ',Url::to(['admin/settings']))?>
    </div>

    <div class="col-md-4 col-xs-12">
        <?=Html::tag('h2','Секции')?>
        <?php foreach(range(1,4) as $key):?>
            <div>
                <?=Html::a('Секция '.$key,Url::to(['admin/sections','section_id'=>$key]))?>
            </div>
        <?php endforeach;?>
    </div>

</div>

views/admin/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\User*/

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Авторизация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Авторизуйтесь для входа в админку</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Вход', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>

views/admin/section1.php
<?php
/**
 * Created by PhpStorm.
 * User: pomazkinis
 * Date: 19.08.2019
 * Time: 12:57
 *
 * @var $this \yii\web\View
 * @var $model \app\models\Sections
 *
 * Секция 1. Редактируем фото на баннере, title и subtitle
 *
 */
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\form\ActiveForm;
use kartik\widgets\FileInput;
use app\components\Helper;
list($initialPreview, $initialPreviewConfig) = $model->initialPreview;

?>
<div class="col-md-12 col-lg-12 review-form">
    <h1>Секция 1 (большой баннер на главной)</h1>
    <div class="">
        <?php $form=ActiveForm::begin([
            'id'=>'input-form',
            'class'=>'',
            'options'=>[
                'enctype' => 'multipart/form-data'
            ],
        ]);?>

        <?= $form->field($model,'active')->dropDownList(['0'=>'Нет',1=>'Да'])?>

        <?= FileInput::widget([
            'name' => 'Sections[images][]',
            'options'=>[
                'multiple'=>true
            ],
            'pluginOptions' => [
                'previewFileType' => 'any',
                'maxFileCount' => 100,
                'maxFileSize'=>10485760,
            ]
        ]);?>

        <?php if($model->hasUploadedImages()):?>
            <h5>Загруженные изображения</h5>
            <div class="uploaded_photos col-md-12">
                <?php foreach($model->hasUploadedImages as $firmImage):?>
                    <?php
                    /* @var $firmImage \app\models\SectionImage*/
                    ?>
                    <div style="width:220px;height:300px" class="parent-block-uploaded-file file-preview-frame krajee-default  kv-preview-thumb col-md-1">
                        <div style="height:200px;overflow: hidden" class="kv-file-content">
                            <?=Html::img(Yii::getAlias('@images_web/') .$firmImage->image,['width'=>200,'height'=>180])?>
                        </div>
                        <div class="file-thumbnail-footer">
                            <div class="file-footer-caption"><?=$firmImage->image?></div>
                            <div class="file-actions clear">
                                <button class="btn btn-danger delete-old-image">-</button>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="can-be-removed-block">
                            <?=Html::input('hidden','Sections[hasUploadedImages][]',$firmImage->image)?>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>
        <?php endif;?>
        <?=Html::error($model, 'hasUploadedImages', ['class'=>'help-block'])?>


        <div class="clearfix"></div>

        <?php foreach (range(1,6) as $v):?>
            <div class="col-md-6 col-lg-6">
                <?=$form->field($model,'image'.$v.'_title')->label('Заголовок к баннеру №'.$v)->textInput()?>
            </div>
            <div class="col-md-6 col-lg-6">
                <?=$form->field($model,'image'.$v.'_description')->label('Описание к баннеру №'.$v)->textInput()?>
            </div>
        <?php endforeach;?>

        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end() ?>
    </div>
</div>

views/admin/section2.php
<?php
/**
 * Created by PhpStorm.
 * User: pomazkinis
 * Date: 19.08.2019
 * Time: 12:57
 *
 * @var $this \yii\web\View
 * @var $model \app\models\Sections
 *
 * Секция 1. Редактируем фото на баннере, title и subtitle
 *
 */
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\form\ActiveForm;
use kartik\widgets\FileInput;
use app\components\Helper;
list($initialPreview, $initialPreviewConfig) = $model->initialPreview;

?>
<div  class="col-md-12 col-lg-12 review-form">
    <h1>Секция 2</h1>
    <div class="">
        <?php $form = ActiveForm::begin([
            'id' => 'section',
            'enableClientValidation' => true,
            'options' => [
                'class' => '',
                'accept-charset' => 'UTF-8'
            ]
        ])
        ?>

        <?= $form->field($model,'active')->dropDownList(['0'=>'Нет',1=>'Да'])?>


        <?=$form->field($model,'title')->textInput()?>

        <?=$form->field($model,'subtitle')->textInput()?>


        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end() ?>
    </div>
</div>

views/admin/section3.php
<?php
/**
 * Created by PhpStorm.
 * User: pomazkinis
 * Date: 19.08.2019
 * Time: 12:57
 *
 * @var $this \yii\web\View
 * @var $model \app\models\Sections
 *
 * Секция 1. Редактируем фото на баннере, title и subtitle
 *
 */
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\form\ActiveForm;
use kartik\widgets\FileInput;
use app\components\Helper;
use mihaildev\ckeditor\CKEditor;
use mihaildev\elfinder\ElFinder;

list($initialPreview, $initialPreviewConfig) = $model->initialPreview;

?>
<div class="col-md-12 col-lg-12 review-form">
    <h1>Секция 3</h1>
    <div class="">
        <?php $form = ActiveForm::begin([
            'id' => 'section',
            'enableClientValidation' => true,
            'options' => [
                'class' => '',
                'accept-charset' => 'UTF-8'
            ]
        ])
        ?>
        <?= $form->field($model,'active')->dropDownList(['0'=>'Нет',1=>'Да'])?>


        <?//=$form->field($model,'title')->textInput()?>


        <?//=$form->field($model,'subtitle')->textInput()?>


            <?=$form->field($model, 'text')->widget(CKEditor::className(), [
                'editorOptions' => ElFinder::ckeditorOptions('elfinder',[]),
            ]);?>

        <?=$form->field($model,'images')
            ->label('Изображения')
            ->widget(FileInput::className(),[
                'options'=>[
                    'multiple'=>true,
                ],
                'pluginOptions' => [
                    'initialPreview'=>$initialPreview,
                    'initialPreviewAsData'=>true,
//                    'initialCaption'=>"Файл импорта",
                    'initialPreviewConfig' => $initialPreviewConfig,
                    'previewFileType' => 'any',
                    'maxFileCount' => 1,
                    'maxFileSize'=>1048576
                ]
            ])?>
        <?php if($model->hasUploadedImages()):?>
            <h5>Загруженные изображения</h5>
            <div class="uploaded_photos col-md-12">
                <?php foreach($model->hasUploadedImages as $firmImage):?>
                    <?php
                    /* @var $firmImage \app\models\SectionImage*/
                    ?>
                    <div style="width:220px;height:300px" class="parent-block-uploaded-file file-preview-frame krajee-default  kv-preview-thumb col-md-1">
                        <div style="height:200px;overflow: hidden" class="kv-file-content">
                            <?=Html::img(Yii::getAlias('@images_web/') .$firmImage->image,['width'=>200,'height'=>180])?>
                        </div>
                        <div class="file-thumbnail-footer">
                            <div class="file-footer-caption"><?=$firmImage->image?></div>
                            <div class="file-actions clear">
                                <button class="btn btn-danger delete-old-image">-</button>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="can-be-removed-block">
                            <?=Html::input('hidden','Sections[hasUploadedImages][]',$firmImage->image)?>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>
        <?php endif;?>
        <?=Html::error($model, 'hasUploadedImages', ['class'=>'help-block'])?>


        <style>
            .fileinput-upload-button{display:none};
        </style>
        <div class="clearfix"></div>

        <?php foreach ([1] as $v):?>
            <div class="col-md-6 col-lg-6">
                <?=$form->field($model,'image'.$v.'_title')->label('Заголовок к баннеру №'.$v)->textInput()?>
            </div>
            <div class="col-md-6 col-lg-6">
                <?=$form->field($model,'image'.$v.'_description')->label('Описание к баннеру №'.$v)->textInput()?>
            </div>
        <?php endforeach;?>

        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end() ?>
    </div>
</div>

views/admin/section4.php
<?php
/**
 * Created by PhpStorm.
 * User: pomazkinis
 * Date: 19.08.2019
 * Time: 12:57
 *
 * @var $this \yii\web\View
 * @var $model \app\models\Sections
 *
 * Секция 1. Редактируем фото на баннере, title и subtitle
 *
 */
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\form\ActiveForm;
use kartik\widgets\FileInput;
use app\components\Helper;

?>
<div class="col-md-12 col-lg-12 review-form">
    <h1>Секция 4 (Галерея)</h1>
    <div class="">
        <?php $form=ActiveForm::begin([
            'id'=>'input-form',
            'class'=>'',
            'options'=>[
                'enctype' => 'multipart/form-data'
            ],
        ]);?>

        <?= $form->field($model,'active')->dropDownList(['0'=>'Нет',1=>'Да'])?>


        <?=$form->field($model,'title')->textInput()?>


        <?=$form->field($model,'subtitle')->textInput()?>
        <?php
        list($initialPreview,$initialPreviewConfig) =\app\models\SectionImage::getInitialPreview($model);
        ?>

        <h3>Фотографии</h3>
        <div class="col-md-12">
            <?= FileInput::widget([
                'name' => 'Sections[images][]',
                'options'=>[
                    'multiple'=>true
                ],
                'pluginOptions' => [
                    'previewFileType' => 'any',
                    'maxFileCount' => 100,
                    'maxFileSize'=>10485760,
                ]
            ]);?>

            <style>

            </style>
            <?php if($model->hasUploadedImages()):?>
                <h5>Загруженные изображения</h5>
                <div class="uploaded_photos col-md-12">
                    <?php foreach($model->hasUploadedImages as $firmImage):?>
                        <?php
                        /* @var $firmImage \app\models\SectionImage*/
                        ?>
                        <div style="width:220px;height:300px" class="parent-block-uploaded-file file-preview-frame krajee-default  kv-preview-thumb col-md-1">
                            <div style="height:200px;overflow: hidden" class="kv-file-content">
                                <?=Html::img(Yii::getAlias('@images_web/') .$firmImage->image,['width'=>200,'height'=>180])?>
                            </div>
                            <div class="file-thumbnail-footer">
                                <div class="file-footer-caption"><?=$firmImage->image?></div>
                                <div class="file-actions clear">
                                    <button class="btn btn-danger delete-old-image">-</button>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="can-be-removed-block">
                                <?=Html::input('hidden','Sections[hasUploadedImages][]',$firmImage->image)?>
                            </div>
                        </div>
                    <?php endforeach;?>
                </div>
            <?php endif;?>
            <?=Html::error($model, 'hasUploadedImages', ['class'=>'help-block'])?>
        </div>
        <div class="clearfix"></div>

        <?php foreach (range(1,6) as $v):?>
            <div class="col-md-6 col-lg-6">
                <?=$form->field($model,'image'.$v.'_title')->label('Заголовок к баннеру №'.$v)->textInput()?>
            </div>
            <div class="col-md-6 col-lg-6">
                <?=$form->field($model,'image'.$v.'_description')->label('Описание к баннеру №'.$v)->textInput()?>
            </div>
        <?php endforeach;?>

        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end() ?>
    </div>
</div>

views/admin/sections.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Sections */
/* @var $form ActiveForm */
?>
<div class="admin-sections">

    <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'active') ?>
        <?= $form->field($model, 'created_at') ?>
        <?= $form->field($model, 'updated_at') ?>
        <?= $form->field($model, 'title') ?>
        <?= $form->field($model, 'subtitle') ?>
        <?= $form->field($model, 'image1_src') ?>
        <?= $form->field($model, 'image1_title') ?>
        <?= $form->field($model, 'image1_description') ?>
        <?= $form->field($model, 'image2_src') ?>
        <?= $form->field($model, 'image2_title') ?>
        <?= $form->field($model, 'image2_description') ?>
        <?= $form->field($model, 'image3_src') ?>
        <?= $form->field($model, 'image3_title') ?>
        <?= $form->field($model, 'image3_description') ?>
        <?= $form->field($model, 'image4_src') ?>
        <?= $form->field($model, 'image4_title') ?>
        <?= $form->field($model, 'image4_description') ?>
        <?= $form->field($model, 'image5_src') ?>
        <?= $form->field($model, 'image5_title') ?>
        <?= $form->field($model, 'image5_description') ?>
        <?= $form->field($model, 'image6_src') ?>
        <?= $form->field($model, 'image6_title') ?>
        <?= $form->field($model, 'image6_description') ?>
        <?= $form->field($model, 'property1_title') ?>
        <?= $form->field($model, 'property1_description') ?>
        <?= $form->field($model, 'property2_title') ?>
        <?= $form->field($model, 'property2_description') ?>
        <?= $form->field($model, 'property3_title') ?>
        <?= $form->field($model, 'property3_description') ?>
        <?= $form->field($model, 'property4_title') ?>
        <?= $form->field($model, 'property4_description') ?>
    
        <div class="form-group">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- admin-sections -->

views/admin/settings.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Settings */
/* @var $form ActiveForm */
?>
<div class="admin-settings">
    <h1>Обшие Настройки</h1>
    <?php $form = ActiveForm::begin(); ?>
        <div class="col-md-8">
            <?= $form->field($model, 'title')->label('Название лендинга (Тег title)') ?>
            <?= $form->field($model, 'kwds')->label('Мета тег keywords') ?>
            <?= $form->field($model, 'description')->label('Мета тег description') ?>
            <?= $form->field($model, 'country')->label('Страна') ?>
            <?= $form->field($model, 'city')->label('Город')  ?>
            <?= $form->field($model, 'region')->label('Регион')  ?>
            <?= $form->field($model, 'street')->label('Улица')  ?>
            <?= $form->field($model, 'building')->label('Дом') ?>
            <?= $form->field($model, 'office')->label('офис') ?>
            <?= $form->field($model, 'postcode')->label('почтовый индекс') ?>
            <?= $form->field($model, 'phone')->label('Телефон') ?>
            <?= $form->field($model, 'email')->label('Email') ?>
            <?= $form->field($model, 'soc_vk') ->label('В контакте (ссылка)')?>
            <?= $form->field($model, 'soc_ok')->label('Одноклассники (ссылка)') ?>
            <?= $form->field($model, 'soc_google')->label('Google+ (ссылка)') ?>
            <div class="form-group">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
            </div>
        </div>


    

    <?php ActiveForm::end(); ?>

</div><!-- admin-settings -->