controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Sections;
use app\models\Settings;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\helpers\Html;
use app\components\Helper;

class SiteController extends AppController
{


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        foreach(range(1,4) as $v)
        {
            ${'section'.$v} = Yii::$app->params['sections'.$v] = Sections::getModel($v);
        }

        $settings = Yii::$app->params['settings'];

        return $this->render('index',compact('section1','section2','section3','section4','settings'));
    }


    /**
     * @return array
     */
    public function actionCall()
    {
        $model = new ContactForm(['scenario'=>ContactForm::SCENARIO_REQUEST]);

        $settings = Settings::getModel();

        if ($model->load(Yii::$app->request->post())  && $model->validate())
        {
            //шлем админу
            Yii::$app->mailer
                ->compose('mail-new-request', ['user'=>$model])
                ->setFrom(env('SENDER_EMAIL','no-reply@eks-massiv.ru'))
                ->setTo($settings->email)
                ->setSubject('Запрос с формы обратный звонок')
                ->send();
            return [
                //'size'=>'large',
                'title'=>'Запрос отправлен',
                'content'=>'Спасибо за обращение! В ближайшее время наши специалисты свяжутся с Вами',
                'footer'=>Html::button('Закрыть',[
                    'class'=>'btn btn-default btn-lg',
                    'data-dismiss'=>'modal',
                ])
            ];
        }

        return [
            'size'=>'small',
            'title'=>'Оставьте Ваши данные, и мы Вам перезвоним',
            'content'=>$this->renderAjax('request_form',compact('model')),
            'footer'=>Html::button('Отправить',[
                'class'=>'btn btn-default btn-lg',
                'type'=>"submit",
            ])
        ];
    }


}

views/site/container.php
<?php
use app\models\SectionImage;
use app\components\Helper;

/**
 * @var $section4 \app\models\Sections
 * @var SectionImage[]  $images array
 * @var $key int
 */

?>

<div class="container">
    <?php foreach($images as $k=>$sectionImage):?>
            <div class="col-md-4">
                <figure class="effect-marley">
                    <a href="<?=Yii::getAlias('@images_web/'.$sectionImage->image)?>" rel="prettyPhoto">
                    <img src="<?=Yii::getAlias('@images_web/'.$sectionImage->image)?>" alt="" class="img-responsive" />
                    </a>
                    <figcaption>
                        <?php
                        $kk = $key*3 + $k;
                        ?>
                        <?php if(isset($section4->images_titles[$kk])):?>
                        <h4><?=$section4->images_titles[$kk]?></h4>
                        <p><?=$section4->images_descriptions[$kk]?></p>
                        <?php endif;?>
                    </figcaption>
                </figure>
            </div>
    <?php endforeach;?>
</div>

views/site/footer.php
<?php
/**
 * Created by PhpStorm.
 * User: pomazkinis
 * Date: 19.08.2019
 * Time: 16:44
 *
 * @var $settings \app\models\Settings
 * @var $section4 \app\models\Sections | null
 */

use app\components\Helper;
use yii\bootstrap\Modal;
$section4  =Yii::$app->params['sections4'];
?>
<footer id="contacts">
    <div class="container">
        <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
            <h4>Контакты</h4>
            <div class="contact-info">
                <ul>
                    <li><i class="fa fa-home fa"></i><?=$settings->postcode?>, <?=$settings->region?>, <?=$settings->city?></li>
                    <li><i class="fa fa-phone fa"></i> <?=$settings->phone ?></li>
                    <li><i class="fa fa-envelope fa"></i> <?=$settings->email?> </li>
                </ul>
            </div>
        </div>

        <?php if($section4 instanceof \app\models\Sections && $section4->active):?>
        <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
            <div class="text-center">

                <h4><?=$section4->title?></h4>
                <?php if($section4->hasUploadedImages()):?>
                    <ul class="sidebar-gallery">
                        <? foreach ($section4->hasUploadedImages as $sectionImage):?>
                            <li>
                                <a href="<?=Yii::getAlias('@images_web/'.$sectionImage->image)?>" rel="prettyPhoto">
                                    <img  src="<?=Yii::getAlias('@images_web/'.$sectionImage->image)?>" alt="" class="img-responsive" />
                                </a>
                            </li>
                        <?php endforeach;?>
                    </ul>
                <?php endif;?>
            </div>
        </div>
        <?php endif;?>

        <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms">
            <div class="">
                <h4>Обратная связь</h4>
                <div class="btn-gamp">
                    <a type="submit" role="modal-remote" href="<?=\yii\helpers\Url::to(['site/call'])?>" class="btn btn-default">Заказать звонок</a>
                </div>
            </div>
        </div>

    </div>
</footer>

<div class="sub-footer">
    <div class="container">
        <div class="social-icon">
            <div class="col-md-4">
                <ul class="social-network">
                    <?php if($settings->soc_google):?>
                    <li><a href="<?=$settings->soc_google?>" class="gplus tool-tip" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
                    <?php endif;?>
                    <?php if($settings->soc_vk):?>
                    <li><a href="<?=$settings->soc_vk?>" class="vkontakte tool-tip" title="vk.com"><i class="fa fa-instagram"></i></a></li>
                    <?php endif;?>
                    <?php if($settings->soc_ok):?>
                    <li><a href="<?=$settings->soc_ok?>" class="ytube tool-tip" title="ok.ru"><i class=""></i></a></li>
                    <?php endif;?>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/site/index.php
<?php

/**
 * @var $this \yii\web\View
 * @var $settings \app\models\Settings
 * @var $section1 \app\models\Sections
 * @var $section2 \app\models\Sections
 * @var $section3 \app\models\Sections
 * @var $section4 \app\models\Sections
 */

use yii\helpers\Url;
use yii\helpers\Html;
use app\components\Helper;

$js=<<<HERE
$(function(){
        $("a[href^='#']").click(function(){
                event.preventDefault;
                var href = $(this).attr("href");
                $("html, body").animate({scrollTop: $(href).offset().top+"px"});
        });
});
HERE;

$this->registerJs($js);

//SEO
$this->title = $settings->title;
//keywords
$this->registerMetaTag([
    'name'=>'keywords',
    'content'=>$settings->kwds
]);
//description
$this->registerMetaTag([
    'name'=>'description',
    'content'=>$settings->description
]);
?>
<?php foreach(range(1,4) as $v):?>
    <?php if(${'section'.$v}->active):?>
        <?php echo $output = $this->render('section'.$v,compact('section'.$v))?>
    <?php endif;?>
<?php endforeach;?>

<?=$this->render('footer',compact('settings'))?>

views/site/request_form.php
<?php

/**
 * @var $this \yii\web\View
 * @var $model \app\models\ContactForm
 */

use kartik\form\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\MaskedInput;

?>
<? $form=ActiveForm::begin()?>

<?=$form->field($model,'name')->label('Как к Вам обращаться?')->textInput(['id'=>'mask'])?>
     <?= $form->field($model, 'phone')->widget(\yii\widgets\MaskedInput::className(), [
      'mask' => '(999) 999-9999',
  ]) ?>

<?php ActiveForm::end()?>
<?
//$this->registerJs('$("#contactform-phone").inputmask({"mask": "(999) 999-9999"});');

views/site/section1.php
<?php
/**
 * Created by PhpStorm.
 * User: pomazkinis
 * Date: 19.08.2019
 * Time: 16:38
 *
 * @var $section1 \app\models\Sections
 * @var $this \yii\web\View
 */

use app\components\Helper;
use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="slider">
    <div id="about-slider">
        <div id="carousel-slider" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->

            <ol class="carousel-indicators visible-xs">
                <?php if ($section1->hasUploadedImages()):?>
                <?php foreach($section1->hasUploadedImages as $k=>$sectionImage):?>
                        <?php
                    /* @var $sectionImage \app\models\SectionImage*/
                        ?>
                        <?=Html::tag('li','',[
                            'data-target'=>'#carousel-slider',
                            'data-slide-to'=>$k,
                            'class'=>$k === 0 ? 'active':''
                        ])?>
                <?php endforeach;?>
                <?php endif;?>
            </ol>

            <div class="carousel-inner">
                <?php foreach($section1->hasUploadedImages as $k=>$sectionImage):?>
                    <div class="item <?=(!$k ? 'active': '')?>">
                        <img src="<?=Yii::getAlias('@images_web/'.$sectionImage->image)?>" class="img-responsive" alt="">
                        <div class="carousel-caption">
                            <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.3s">
                                <h2><span><?=$section1->images_titles[$k]?></span></h2>
                            </div>
                            <div class="col-md-10 col-md-offset-1">
                                <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.6s">
                                    <p style="background: none"><?=$section1->images_descriptions[$k]?></p>
                                </div>
                            </div>
                            <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.9s"> </div>
                        </div>
                    </div>
                <?php endforeach;?>


            <a class="left carousel-control hidden-xs" href="#carousel-slider" data-slide="prev">
                <i class="fa fa-angle-left"></i>
            </a>

            <a class=" right carousel-control hidden-xs" href="#carousel-slider" data-slide="next">
                <i class="fa fa-angle-right"></i>
            </a>
        </div>
        <!--/#carousel-slider-->
    </div>
    <!--/#about-slider-->
</div>
<!--/#slider-->

views/site/section2.php
<?php
/* @var $section2 \app\models\Sections*/
/* @var $this \yii\web\View*/

use app\components\Helper;
use yii\helpers\Html;
use yii\helpers\Url;
use johnitvn\ajaxcrud\CrudAsset;


CrudAsset::register($this);
?>
<div id="section2" class="about">
    <div class="container">
        <div class="text-center">
            <h2><?=$section2->subtitle?></h2>
            <div class="col-md-10 col-md-offset-1">
                <p><?//=$section2->subtitle?></p>
            </div>
        </div>

        <div style="display: flex; justify-content: center;align-items: center; width:100%">
            <div class="btn-gamp">
                <?=Html::a('Заказать звонок',Url::to(['site/call']),[
                        'title'=>'Заказать звонок',
                        'class'=>'call-button',
                        'type'=>'submit',
                        'role'=>'modal-remote'
                ])?>
            </div>
        </div>
    </div>
</div>
<hr>

views/site/section3.php
<?php
/**
 * Created by PhpStorm.
 * User: pomazkinis
 * Date: 19.08.2019
 * Time: 16:43
 */
/* @var $section3 \app\models\Sections*/
/* @var $this \yii\web\View*/

use app\components\Helper;
use yii\helpers\Html;
use yii\helpers\Url;
//Helper::debug($section3);
?>

<div id="section3" class="services">
    <div class="container">
        <div class="text-center">
            <h2><?=$section3->text?></h2>
        </div>
    </div>
</div>
<section class="action">
    <div class="container">
        <div class="left-text hidden-xs">
            <h4><?=$section3->image1_title?></h4>
            <p><?=$section3->image1_description?></p>
        </div>
        <div class="right-image hidden-xs" style="background-image: url(<?=Yii::getAlias('@images_web/'.$section3->sectionImages[0]->image ?? null)?>)"></div>
    </div>
</section>

9049894834

views/site/section4.php
<?php
/**
 * Created by PhpStorm.
 * User: pomazkinis
 * Date: 19.08.2019
 * Time: 16:44
 */

/* @var $section4 \app\models\Sections*/
/* @var $this \yii\web\View*/

use app\components\Helper;
use yii\helpers\Html;
use yii\helpers\Url;
?>

<div id="section4" class="gallery">
    <div class="text-center">
        <h2><?=$section4->title?></h2>
        <p><?=$section4->subtitle?></p>
    </div>

    <?php if($section4->hasUploadedImages()):?>
        <?php foreach(array_chunk($section4->hasUploadedImages, 3) as $k=>$group):?>
            <?=$this->render('container', [
                    'images'=>$group,
                    'key'=>$k,
                    'section4'=>$section4
            ])?>
        <?php endforeach;?>
    <?php endif?>
</div>